### ISSUE TITLE
keycloakSecurityConfig 

### ISSUE THREAD

**Issue by Wo-com** [larmic/spring-boot-demos#100]
┌──->──┐
|  keycloakSecurityConfig (field private org.keycloak.adapters.KeycloakConfigResolver org.keycloak.adapters.springsecurity.config.KeycloakWebSecurityConfigurerAdapter.keycloakConfigResolver)
└──<-──┘

**Comment by larmic** [comment]
Hi,

unfortunately, I don't understand your error. can you describe the problem a little more precisely?
