### ISSUE TITLE
Add Building Docker Images using Google Jib

### ISSUE THREAD

**Issue by MSC-AA** [larmic/spring-boot-demos#222]
Google provides the Tool [Jib] (https://github.com/GoogleContainerTools/jib) to create Docker Images for Java Projects.

An example can be found [here](https://cloud.google.com/java/getting-started/jib)

One Advantage is that the resulting images are small in size and Jib utilizes caching to make the build process fast. 

One disadvantage of this tool is that it encapsulates the whole process of creating a docker image, so one cannot see the "actual" Dockerfile that was created

**Comment by larmic** [comment]
done
