### ISSUE TITLE
Preparation for spring with lambda 

### ISSUE THREAD

**Issue by DanilloLadu** [larmic/spring-boot-demos#366]
https://github.com/larmic/spring-boot-demos/blob/c54d9e717cd64f8d3470f2f79a4a4c77ad4a1b72/spring-boot-keycloak/src/main/java/de/larmic/keycloak/service1/security/KeycloakSecurityConfig.java#L43C1-L56C29

nothing wrong just updated you code for lambda, maybe  its not perfect way
-----------------
    import static org.springframework.security.config.Customizer.withDefaults;

    @Value("${spring.security.oauth2.client.registration.keycloak.client-id}")
    private String clientId;

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {

        http.authorizeHttpRequests(it -> it
                        .requestMatchers("/unsecure/*").permitAll()
                        .requestMatchers("/secure/*").hasAnyRole("admin", "custom_realm_role"))
                .csrf(AbstractHttpConfigurer::disable);

        http.oauth2Login(withDefaults())
                .logout(logout -> logout.logoutSuccessUrl("/"));
        http.oauth2ResourceServer(oauth -> oauth
                .jwt(jwtConfigurer -> jwtConfigurer
                        .jwtAuthenticationConverter(
                                jwtAuthenticationConverter(new KeycloakGrantedAuthoritiesConverter(clientId))
                        )
                )
        );

        return http.build();
    }

**Comment by larmic** [comment]
Thx and done!
